SEARCH_MOVIE_METRIC_COUNT_NAME='search_hit_by_movie_count'
SEARCH_ACTOR_METRIC_COUNT_NAME='search_total_hit'
SEARCH_METRIC_COUNT_NAME='search_hit_count'
SEARCH_API_METRIC_COUNT_NAME='api_calls_count'
SEARCH_API_METRIC_HISTOGRAM_NAME='API_LATENCY'
SEARCH_METRIC_GAUGE_NAME='search_hit_guage_total_time'
SEARCH_MOVIE_METRIC_COUNT_DESC='Tell search hit counts made with movies'
SEARCH_ACTOR_METRIC_COUNT_DESC='Tell search hit counts made with actor'
SEARCH_METRIC_COUNT_DESC='Tell search hit counts made without any query string'
SEARCH_METRIC_GAUGE_DESC='Tell search hit guage value showing total time taking'
SEARCH_API_METRIC_COUNT_DESC='Total no of api hits made'
SEARCH_API_METRIC_HISTOGRAM_DESC='api latency'

